questions =  [
    {"id": 0, "question": "Eta and Iota were Category 5.", "effects": {"wee": 1}},
    {"id": 1, "question": "I am educated enough to issue accurate tropical forecasts.", "effects": {"wee": -1}},
    {"id": 2, "question": "I am a tropical weenie.", "effects": {"wee": 1}},
    {"id": 3, "question": "Recon efforts should be expanded to get more accurate data.", "effects": {"inn": 1, "wee": -1}},
    {"id": 4, "question": "The NHC should work to make their forecasts more accessible.", "effects": {"inn": 1}},
    {"id": 5, "question": "NOAA and the NHC need more funding.", "effects": {"inn": 1}},
    {"id": 6, "question": "The NHC overestimates windspeeds.", "effects": {"wee": 1}},
    {"id": 7, "question": "Most NHC ratings are fair.", "effects": {"wee": -1}},
    {"id": 8, "question": "They should have kept the Greek names.", "effects": {"inn": -1, "wee": 1}},
    {"id": 9, "question": "The Emergency Alert System should be used to communicate Hurricane Watches and Warnings.", "effects": {"inn": 1}},
    {"id": 10, "question": "Most 155 mph hurricanes are just undersampled Category 5s.", "effects": {"wee": 1}},
    {"id": 11, "question": "I enjoy hurricanes as long as they don't do much damage.", "effects": {"wee": -1}},
    {"id": 12, "question": "Name retirement should be based on windspeed.", "effects": {"inn": 1}},
    {"id": 13, "question": "Hurricanes should be rated by damage rather than estimated windspeed.", "effects": {"inn": 1, "wee": 1}},
    {"id": 14, "question": "Years like 2020 will happen every year.", "effects": {"wee": 1}},
    {"id": 15, "question": "Hurricanes should start being named One, Two, etc. again.", "effects": {"inn": -1}},
    {"id": 16, "question": "People should rely on the NHC for outlooks instead of YouTube channels.", "effects": {"wee": -1}},
    {"id": 17, "question": "I know more than the NHC.", "effects": {"wee": 1}},
	{"id": 18, "question": "The criteria for Extreme Wind Warnings should be pushed down to 100 mph.", "effects": {"inn": 1}},
	{"id": 19, "question": "Raw Dvorak should be used to determine hurricane strength.", "effects": {"inn": 1, "wee": 1}},
	{"id": 20, "question": "Advanced Dvorak/ADT should be used to determine hurricane strength.", "effects": {"inn": 1, "wee": -1}},
	{"id": 21, "question": "The NHC should revert to their old outlooks.", "effects": {"wee": 1}},
	{"id": 22, "question": "There should be a Category 6 for storms above 210 mph.", "effects": {"inn": 1, "wee": 1}},
	{"id": 23, "question": "Windspeed doesn't matter, but impact does.", "effects": {"wee": -1}},
	{"id": 24, "question": "Surface observations should be used to find and determine the strength of hurricanes instead of satellites.", "effects": {"inn": -1}},
	{"id": 25, "question": "The better a storm looks, the stronger it is.", "effects": {"wee": 1}},
	{"id": 26, "question": "The NHC should forecast in all basins.", "effects": {"inn": 1}},
	{"id": 27, "question": "It is possible to see a hurricane equal to or stronger than Patricia in the Atlantic.", "effects": {"wee": 1}},
	{"id": 28, "question": "Matthew was a Category 5.", "effects": {"wee": 0.5}},
	{"id": 29, "question": "The NHC underestimates windspeeds.", "effects": {"wee": 1}},
	{"id": 30, "question": "I would be excited if a hurricane were to hit me.", "effects": {"wee": 1}},
	{"id": 31, "question": "People should be taught hurricane safety at a young age to mitigate future loss of life.", "effects": {"inn": 1, "wee": -1}},
	{"id": 32, "question": "Storms should only be tracked by the NHC if they are going to make landfall somewhere.", "effects": {"inn": -1}},
	{"id": 33, "question": "I don't think hurricanes are impactful as people say they are.", "effects": {"wee": 1}},
	{"id": 34, "question": "I know when to and when not to joke about a hurricane and its potential impacts.", "effects": {"wee": -1}},
	{"id": 35, "question": "Invests should be warned to give people who could potentially be impacted a very early warning.", "effects": {"inn": 1}}
];
