questions =  [
    {"id": 0, "question": "Long term goals are more important than short term goals.", "effects": {"for": -1}},
    {"id": 1, "question": "The Supreme Court made the correct decision in the fourth election.", "effects": {"soc": -1}},
    {"id": 2, "question": "Experience should be the most important factor in deciding who to vote for.", "effects": {"pop": -1}},
    {"id": 3, "question": "DM campaigning should be allowed.", "effects": {"for": 1}},
    {"id": 4, "question": "We should not be afraid to introduce taxes if need be.", "effects": {"soc": 1}},
    {"id": 5, "question": "We should not be afraid to vote for members that have less experience than others.", "effects": {"pop": 1}},
    {"id": 6, "question": "We should give the people that are less active positions.", "effects": {"for": 1}},
    {"id": 7, "question": "The general community should be prioritized over individual rights.", "effects": {"soc": 1}},
    {"id": 8, "question": "Staff members are favored to be voted into public positions.", "effects": {"pop": 1}},
    {"id": 9, "question": "The NGEC should stay private.", "effects": {"for": -1}},
    {"id": 10, "question": "The electoral voting system has failed without any way of redemption.", "effects": {"soc": -1}},
    {"id": 11, "question": "Staff members should be allowed to run for public positions without restraint.", "effects": {"pop": -1}},
    {"id": 12, "question": "Change should be the top focus of those in the White House.", "effects": {"for": 1}},
    {"id": 13, "question": "More pre-reset parts of the server should be added.", "effects": {"soc": 1}},
    {"id": 14, "question": "I align with the Independent People's Party more than the Commune Party.", "effects": {"pop": 1}},
    {"id": 15, "question": "Exile should remain a part of the Mock Government criminal code.", "effects": {"for": -1}},
    {"id": 16, "question": "Implementation of regions was too rushed.", "effects": {"soc": -1}},
    {"id": 17, "question": "Clever is more Establishment than Populist.", "effects": {"pop": -1}},
    {"id": 18, "question": "Quaky has served his time properly.", "effects": {"for": 1}},
    {"id": 19, "question": "The idea of mayors was ahead of its time.", "effects": {"soc": 1}},
    {"id": 20, "question": "Stan/PA were elected because they were the best candidates on the ballot.", "effects": {"pop": 1}},
    {"id": 21, "question": "Henry should have been convicted of voter fraud by the Supreme Court.", "effects": {"for": -1}},
    {"id": 22, "question": "The idea of Regional Courts is flawed.", "effects": {"soc": -1}},
    {"id": 23, "question": "I voted for Niko/Wooub over Panda/Pyro in the June 3rd-4th election.", "effects": {"pop": -1}},
    {"id": 24, "question": "We should reform systems that can be better, even if they are working fine.", "effects": {"for": 1}},
    {"id": 25, "question": "The House of Representatives should become a legislative body for all bills.", "effects": {"soc": 1}},
    {"id": 26, "question": "We should elect newer Mock Government members rather than older ones.", "effects": {"pop": 1}}
];
